## test4j断言 ##
### 什么是断言 ###
** 断言的作用简而言之是判断一个变量的值是否符合预期**

在从JDK1.4开始，java引入了assert关键字，但Java默认在执行时是不启动断言检查的，这时候java代码中的所有assert语句都是 不生效的,运行是就和注释一样，无声无息！如果要开启断言检查，则需要用开关-enableassertions或-ea来开启。但大家在使用junit和testng测试框架时，是无需关心这个参数的，框架在启动测试时，本身会把这个开关打开的。

```java
public class AssertDemo extends Test4J {
    @Test
    public void test() {
        assert false;
        System.out.println("Hello, Assertion!");
    }
}
```
执行test方法，控制台默认情况下回输出下列信息：
<pre><code>WARNING: If JMockit isn't initialized. Please check that your JVM is started with command option:
<span style="color:red;">     -javaagent:D:\m2\org\test4j\test4j.nodep\2.0.6\test4j.nodep-2.0.6.jar</span>
WARNING: No custom configuration file test4j.properties found.
INFO: No local configuration file test4j-local.properties found.
WARNING: can't find class false in classpath, so disabled module[jmockit]
WARNING: can't find class false in classpath, so disabled module[spring]
Hello, Assertion!</code></pre>

虽然代码中有 <code>assert false;</code>但java代码继续执行到了System.out.println代码行，这是因为断言的开关没有打开， 在测试方法中加上vm参数<code>-ea</code>,再次执行，或的结果如下：
<pre><code><span style="color:red;">java.lang.AssertionError</span>
	at org.test4j.example.assertions.AssertDemo.test(AssertDemo.java:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.test4j.junit.statement.MethodAroundStatement.evaluate(MethodAroundStatement.java:35)
	at org.test4j.junit.statement.TestAroundStatement.evaluate(TestAroundStatement.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.test4j.tools.reflector.MethodAccessor.invoke(MethodAccessor.java:49)
	at org.test4j.tools.reflector.MethodAccessor.invokeUnThrow(MethodAccessor.java:72)
	at org.test4j.tools.commons.MethodHelper.invokeUnThrow(MethodHelper.java:267)
	at org.test4j.junit.Test4JRunner$1.evaluate(Test4JRunner.java:86)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
</code></pre>

这时候，<code>assert false</code>抛出了AssertionError错误，阻止程序继续运行System.out.println代码行。


**注意**
assert抛出的是错误（Error），不是异常（Exception）
```java
    try {
        throw new AssertionError("test");
    } catch (Exception e) {
        System.out.println(e);
    }
```
是无法捕获到断言错误的。 <code>catch(Throwable e)</code>是可以捕获到的。
```java
    try {
        throw new AssertionError("test");
    } catch (Throwable e) {
        System.out.println(e);
    }
```
让我们来看看AssertionError的类层次
<pre>
<a>java.lang.Object</a>
<a>&nbsp;&nbsp;&nbsp;&nbsp;java.lang.Throwable</a>
<a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;java.lang.Error</a>
<a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;java.lang.AssertionError</a>
<a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;java.lang.Exception</a>
<a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;java.lang.RuntimeException</a>
</pre>
从类层次中，可以看出断言错误是个Error，不是Exception。

### junit断言 ###
junit和testng提供一些基本的断言功能
- assertEquals: 判断对象是否相等

```
函数原型1：assertEquals([String message],expected,actual) 
参数说明： 
	message: 是个可选的消息，假如提供，将会在发生错误时报告这个消息。 
	expected: 是期望值，通常都是用户指定的内容
```

```
函数原型2：assertEquals([String message],expected,actual,tolerance) 
参数说明： 
	message: 是个可选的消息，假如提供，将会在发生错误时报告这个消息。 
　　expected: 是期望值，通常都是用户指定的内容。 
　　actual: 是被测试的代码返回的实际值。 
　　tolerance: 是误差参数，参加比较的两个浮点数在这个误差之内则会被认为是相等的。 
```
- assertTrue:该断言用来验证给定的布尔型值是否为真，假如结果为假，则验证失败。

```
函数原型：assertTrue ([String message],Boolean condition) 
参数说明：
	message: 是个可选的消息，假如提供，将会在发生错误时报告这个消息。 
	condition: 是待验证的布尔型值。 
例: assertTrue("true",1==1)
```

- assertFalse: 该断言用来验证给定的布尔型值是否为假，假如结果为真，则验证失败

```
函数原型：assertFalse([String message],Boolean condition) 
例: assertFalse("false",2==1)
``` 

- assertNull: 该断言用来验证给定的对象是否为null，假如不为null，则验证失败

```
函数原型：assertNull([String message],Object object) 
参数说明： 
	message是个可选的消息，假如提供，将会在发生错误时报告这个消息。 
	object是待验证的对象。
例：assertNull("null",null)
```

- assertNotNull: 该断言用来验证给定的对象是否为非null，假如为null，则验证失败

```
例：assertNotNull("not null",new String());
```

- assertSame: 该断言用来验证expected参数和actual参数所引用的是否是同一个对象，假如不是，则验证失败

```
参数说明： 
	message是个可选的消息，假如提供，将会在发生错误时报告这个消息。 
　　expected是期望值。 
　　actual是被测试的代码返回的实际值。
例：assertSame("same",2,4-2); 
```

- assertNotSame: 该断言用来验证expected参数和actual参数所引用的是否是不同对象，假如所引用的对象相同，则验证失败

```
函数原型：assertNotSame ([String message], expected,actual) 
例：assertNotSame("not same",2,4-3); 
```

- fail：该断言会使测试立即失败，通常用在测试不能达到的分支上（如异常）

```
函数原型：fail([String message]) 
参数说明： 
	message是个可选的消息，假如提供，将会在发生错误时报告这个消息。
```

junit&testng虽然提供了比较基础的断言功能，但在实战中常常会碰到很复杂的情况，如果仅仅使用上述的断言来组合，会使得断言代码量和复杂性急剧上升，不利于测试， test4j提供了很多便利的语法来完成复杂场景的断言。